### PR TITLE
Avoid treating loadModel warnings as errors

### LINKED ISSUE #17: Since latest update, Highs returns "unable to read LP model" while the error should be "infeasible problem"
Hello,

As per issue title.

Reproducer:

Minimize
 obj: x1
Subject To
 c1: 1 x0 1 x1 = 1
Bounds
 0 <= x1 <= 1
 1.1 <= x2 <= 1
End
     
This now results in an (incorrect) LP-model reading error, while with the previous release, the error was that the problem is infeasible (correct), c.f. screenshot:

image

By the way, not sure the problem is with the JavaScript wrapper, because I see there was an update of Highs version.

_Edit: I saw there were some changes in the parsing out HiGHS output as well (https://github.com/lovasoa/highs-js/commit/535a0d3df2981856599255e28f3793eb95702e8e), so, maybe one of these now incorrectly manage this infeasible problem._

Cheers,

Roman

### PR DESCRIPTION
**Pull request by fuglede**
The C API function `readModel` can return one of three values, cf.

```c
enum class HighsStatus { kError = -1, kOk = 0, kWarning = 1 };
```

and in the corresponding piece of JavaScript, `assert_ok` would make the requirement that result is 0. Here, we change that to require only that the result is not -1, thus allowing `solve` to continue in case the loading of the model causes a warning.

A different approach here could have been to stick to `assert_ok`, but give it an argument a la `allowedReturnValues`.

Note also that it is possible for `readModel` to error completely (as is the case for the test `test_invalid_model`), so we make sure to explicitly check for that as well.

It could be useful enough to actually provide the warning message to the user somehow, but figuring out what the warning message is might be some work; it is not part of the pretty output, for example.

This closes #17.

### CODE REVIEW

**Comment by lovasoa** [comment]
I think you should change assert_ok instead of reimplementing it. Otherwise we are still going to throw an error when highs emits a warning in other parts of the code.

**Comment by fuglede** [comment]
> I think you should change assert_ok instead of reimplementing it. Otherwise we are still going to throw an error when highs emits a warning in other parts of the code.

Makes sense, and done; I hadn't checked the other usages and assumed that it could be used for things that didn't correspond to `HighsStatus`, but I can see that that's not the case.

File: src/post.js [hunk 1]
```diff
@@ -200,6 +200,8 @@ function assert_ok(fn, action) {
   } catch (e) {
     err = e;
   }
-  if (err !== 0)
+  // Allow HighsStatus::kWarning (0) and HighsStatus::kWarning (1) but
```
Comment (lovasoa) [inline src/post.js:203]:
```suggestion
  // Allow HighsStatus::kOk (0) and HighsStatus::kWarning (1) but 
```

File: src/post.js [hunk 2]
```diff
@@ -200,6 +200,8 @@ function assert_ok(fn, action) {
   } catch (e) {
     err = e;
   }
-  if (err !== 0)
+  // Allow HighsStatus::kWarning (0) and HighsStatus::kWarning (1) but 
+  // disallow other values, such as e.g. HighsStatus::kError (-1).
+  if (!(err in [0, 1]))
```
Comment (lovasoa) [inline src/post.js:205]:
```suggestion
  if (err !== 0 || err !== 1)
```

Comment (lovasoa) [reply src/post.js:205]: @fuglede `in` doesn't do what you think on an array.

**Review by lovasoa — CHANGES_REQUESTED** [review]

File: src/post.js [hunk 3]
```diff
@@ -200,6 +200,8 @@ function assert_ok(fn, action) {
   } catch (e) {
     err = e;
   }
-  if (err !== 0)
+  // Allow HighsStatus::kOk (0) and HighsStatus::kWarning (1) but 
+  // disallow other values, such as e.g. HighsStatus::kError (-1).
+  if (err !== 0 || err !== 1)
```
Comment (lovasoa) [inline src/post.js:205]:
```suggestion
  if (err !== 0 && err !== 1)
```

File: tests/test.js [hunk 4]
```diff
@@ -325,6 +325,56 @@ function test_unbounded(Module) {
...
+Subject To
+c1: 1 x0 + 1 x1 = 1
+Bounds
+0 <= x1 <= 1
+1.1 <= x2 <= 1
+End`);
+  assert.deepStrictEqual(sol, {
+    IsLinear: true,
+    IsQuadratic: false,
+    Status: 'Infeasible',
```
Comment (lovasoa) [inline tests/test.js:344]:
```suggestion
    Status: 'Infeasible',
    ObjectiveValue: 0,
```

File: src/post.js (hunk 2 above)
Comment (fuglede) [reply src/post.js]: I guess for this particular array it more or less does, but yeah, makes more sense to be explicit.
